version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taproost-service
    expose:
      - ${PORT}
    networks:
      - nginx_proxy
    environment:
      - STAGE=dev
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_EXPIRED=${JWT_ACCESS_EXPIRED}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}

networks:
  nginx_proxy:
    external: true
